namespace DatabaseSetup.TableData
{
    internal class DescriptionsData
    {
        internal static string Query = @"IF((SELECT count(*) FROM Descriptions)=0) BEGIN insert into Descriptions (ID, Description) values (1, 'A basic sword that deals damage to an enemy.');
insert into Descriptions (ID, Description) values (2, 'A basic potion that restores 50 health points.');
insert into Descriptions (ID, Description) values (3, 'A claw from a crab. It has no value.');
insert into Descriptions (ID, Description) values (4, 'Cras non velit nec nisi vulputate nonummy.');
insert into Descriptions (ID, Description) values (5, 'In quis justo.');
insert into Descriptions (ID, Description) values (6, 'Pellentesque viverra pede ac diam.');
insert into Descriptions (ID, Description) values (7, 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into Descriptions (ID, Description) values (8, 'Mauris sit amet eros.');
insert into Descriptions (ID, Description) values (9, 'Cras pellentesque volutpat dui.');
insert into Descriptions (ID, Description) values (10, 'Ut tellus. Nulla ut erat id mauris vulputate elementum.');
insert into Descriptions (ID, Description) values (11, 'Duis mattis egestas metus. Aenean fermentum.');
insert into Descriptions (ID, Description) values (12, 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.');
insert into Descriptions (ID, Description) values (13, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.');
insert into Descriptions (ID, Description) values (14, 'Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into Descriptions (ID, Description) values (15, 'Ut tellus.');
insert into Descriptions (ID, Description) values (16, 'Nullam molestie nibh in lectus. Pellentesque at nulla.');
insert into Descriptions (ID, Description) values (17, 'Pellentesque ultrices mattis odio.');
insert into Descriptions (ID, Description) values (18, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into Descriptions (ID, Description) values (19, 'Aliquam non mauris. Morbi non lectus.');
insert into Descriptions (ID, Description) values (20, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into Descriptions (ID, Description) values (21, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.');
insert into Descriptions (ID, Description) values (22, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
insert into Descriptions (ID, Description) values (23, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into Descriptions (ID, Description) values (24, 'Donec ut mauris eget massa tempor convallis.');
insert into Descriptions (ID, Description) values (25, 'Nulla facilisi.');
insert into Descriptions (ID, Description) values (26, 'Morbi vel lectus in quam fringilla rhoncus.');
insert into Descriptions (ID, Description) values (27, 'Etiam faucibus cursus urna.');
insert into Descriptions (ID, Description) values (28, 'Vivamus vel nulla eget eros elementum pellentesque.');
insert into Descriptions (ID, Description) values (29, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.');
insert into Descriptions (ID, Description) values (30, 'Nulla tellus.');
insert into Descriptions (ID, Description) values (31, 'Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into Descriptions (ID, Description) values (32, 'Donec quis orci eget orci vehicula condimentum.');
insert into Descriptions (ID, Description) values (33, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into Descriptions (ID, Description) values (34, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into Descriptions (ID, Description) values (35, 'Praesent blandit lacinia erat.');
insert into Descriptions (ID, Description) values (36, 'Cras pellentesque volutpat dui.');
insert into Descriptions (ID, Description) values (37, 'Aenean auctor gravida sem.');
insert into Descriptions (ID, Description) values (38, 'Vivamus vestibulum sagittis sapien.');
insert into Descriptions (ID, Description) values (39, 'Integer tincidunt ante vel ipsum.');
insert into Descriptions (ID, Description) values (40, 'In sagittis dui vel nisl.');
insert into Descriptions (ID, Description) values (41, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.');
insert into Descriptions (ID, Description) values (42, 'Donec ut mauris eget massa tempor convallis.');
insert into Descriptions (ID, Description) values (43, 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into Descriptions (ID, Description) values (44, 'Fusce consequat.');
insert into Descriptions (ID, Description) values (45, 'Nunc rhoncus dui vel sem.');
insert into Descriptions (ID, Description) values (46, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into Descriptions (ID, Description) values (47, 'Morbi a ipsum. Integer a nibh.');
insert into Descriptions (ID, Description) values (48, 'Suspendisse potenti.');
insert into Descriptions (ID, Description) values (49, 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into Descriptions (ID, Description) values (50, 'Etiam vel augue. Vestibulum rutrum rutrum neque.');
insert into Descriptions (ID, Description) values (51, 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into Descriptions (ID, Description) values (52, 'Donec semper sapien a libero. Nam dui.');
insert into Descriptions (ID, Description) values (53, 'Etiam vel augue.');
insert into Descriptions (ID, Description) values (54, 'Suspendisse potenti.');
insert into Descriptions (ID, Description) values (55, 'Proin eu mi. Nulla ac enim.');
insert into Descriptions (ID, Description) values (56, 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.');
insert into Descriptions (ID, Description) values (57, 'Suspendisse potenti.');
insert into Descriptions (ID, Description) values (58, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.');
insert into Descriptions (ID, Description) values (59, 'Nunc purus.');
insert into Descriptions (ID, Description) values (60, 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into Descriptions (ID, Description) values (61, 'Proin interdum mauris non ligula pellentesque ultrices.');
insert into Descriptions (ID, Description) values (62, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into Descriptions (ID, Description) values (63, 'Fusce posuere felis sed lacus.');
insert into Descriptions (ID, Description) values (64, 'In eleifend quam a odio.');
insert into Descriptions (ID, Description) values (65, 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into Descriptions (ID, Description) values (66, 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into Descriptions (ID, Description) values (67, 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.');
insert into Descriptions (ID, Description) values (68, 'In hac habitasse platea dictumst.');
insert into Descriptions (ID, Description) values (69, 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.');
insert into Descriptions (ID, Description) values (70, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into Descriptions (ID, Description) values (71, 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.');
insert into Descriptions (ID, Description) values (72, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.');
insert into Descriptions (ID, Description) values (73, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into Descriptions (ID, Description) values (74, 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.');
insert into Descriptions (ID, Description) values (75, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into Descriptions (ID, Description) values (76, 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into Descriptions (ID, Description) values (77, 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.');
insert into Descriptions (ID, Description) values (78, 'Fusce consequat.');
insert into Descriptions (ID, Description) values (79, 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.');
insert into Descriptions (ID, Description) values (80, 'Aliquam sit amet diam in magna bibendum imperdiet.');
insert into Descriptions (ID, Description) values (81, 'Quisque porta volutpat erat.');
insert into Descriptions (ID, Description) values (82, 'Nulla justo.');
insert into Descriptions (ID, Description) values (83, 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.');
insert into Descriptions (ID, Description) values (84, 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into Descriptions (ID, Description) values (85, 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into Descriptions (ID, Description) values (86, 'Etiam vel augue.');
insert into Descriptions (ID, Description) values (87, 'Suspendisse accumsan tortor quis turpis.');
insert into Descriptions (ID, Description) values (88, 'Aenean lectus.');
insert into Descriptions (ID, Description) values (89, 'Curabitur in libero ut massa volutpat convallis.');
insert into Descriptions (ID, Description) values (90, 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
insert into Descriptions (ID, Description) values (91, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.');
insert into Descriptions (ID, Description) values (92, 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into Descriptions (ID, Description) values (93, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into Descriptions (ID, Description) values (94, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into Descriptions (ID, Description) values (95, 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.');
insert into Descriptions (ID, Description) values (96, 'Vivamus tortor.');
insert into Descriptions (ID, Description) values (97, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.');
insert into Descriptions (ID, Description) values (98, 'Maecenas pulvinar lobortis est.');
insert into Descriptions (ID, Description) values (99, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into Descriptions (ID, Description) values (100, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.'); END";
    }
}
