namespace DatabaseSetup.TableData
{
    internal class ItemsData
    {
        internal static string Query = @"IF((SELECT count(*) FROM Items)=0) BEGIN insert into Items (ID, Name, Price, DescriptionID, TypeID) values (1, 'Steel Sword', 10.99, 1, 1);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (2, 'Red Potion', 0.50, 2, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (3, 'Crab Claw', 0.01, 3, 3);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (4, 'Wine - Casablanca Valley', 23.35, 4, 1);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (5, 'Cassis', 65.21, 5, 1);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (6, 'Bread - Rosemary Focaccia', 81.48, 6, 1);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (7, 'Bread - White Epi Baguette', 14.16, 7, 3);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (8, 'Jerusalem Artichoke', 26.81, 8, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (9, 'Shrimp - 16 - 20 Cooked, Peeled', 10.22, 9, 1);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (10, 'Dill - Primerba, Paste', 30.72, 10, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (11, 'Salad Dressing', 85.18, 11, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (12, 'Wine - Riesling Dr. Pauly', 23.24, 12, 1);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (13, 'Veal - Inside', 84.84, 13, 1);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (14, 'Chicken - Ground', 84.44, 14, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (15, 'Jolt Cola - Electric Blue', 56.04, 15, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (16, 'Grapes - Red', 95.24, 16, 3);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (17, 'Pasta - Shells, Medium, Dry', 51.92, 17, 3);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (18, 'Soap - Pine Sol Floor Cleaner', 67.51, 18, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (19, 'Flour - Masa De Harina Mexican', 82.38, 19, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (20, 'Bread - Kimel Stick Poly', 57.86, 20, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (21, 'Tomatoes - Plum, Canned', 32.41, 21, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (22, 'Cake - Cake Sheet Macaroon', 66.72, 22, 1);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (23, 'Lighter - Bbq', 97.32, 23, 3);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (24, 'Cheese - Swiss Sliced', 30.84, 24, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (25, 'Curry Paste - Green Masala', 48.16, 25, 1);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (26, 'Coffee Cup 16oz Foam', 49.87, 26, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (27, 'Chicken - Whole Fryers', 3.31, 27, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (28, 'Cheese - Havarti, Roasted Garlic', 11.62, 28, 3);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (29, 'Beans - Black Bean, Preserved', 78.07, 29, 1);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (30, 'Trout - Smoked', 25.54, 30, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (31, 'Olives - Green, Pitted', 78.9, 31, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (32, 'Bread - Flat Bread', 95.14, 32, 1);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (33, 'Horseradish - Prepared', 74.75, 33, 1);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (34, 'Cheese - Gouda', 65.63, 34, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (35, 'Ecolab Silver Fusion', 59.95, 35, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (36, 'Wine La Vielle Ferme Cote Du', 67.48, 36, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (37, 'Tea - Herbal Sweet Dreams', 74.2, 37, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (38, 'Hog / Sausage Casing - Pork', 13.96, 38, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (39, 'Sauce - Marinara', 15.42, 39, 1);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (40, 'Cotton Wet Mop 16 Oz', 45.79, 40, 3);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (41, 'Parsnip', 96.52, 41, 1);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (42, 'Pepper - Black, Ground', 31.13, 42, 3);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (43, 'French Pastry - Mini Chocolate', 31.66, 43, 1);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (44, 'Calypso - Black Cherry Lemonade', 76.56, 44, 3);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (45, 'Flax Seed', 57.52, 45, 3);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (46, 'Egg Patty Fried', 76.64, 46, 3);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (47, 'Cup - 3.5oz, Foam', 69.24, 47, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (48, 'Nantucket - 518ml', 78.08, 48, 3);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (49, 'Contreau', 48.98, 49, 3);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (50, 'Bread - 10 Grain Parisian', 48.46, 50, 3);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (51, 'Lettuce - Red Leaf', 84.06, 51, 3);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (52, 'Cookies - Assorted', 76.74, 52, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (53, 'Pork - Backfat', 23.36, 53, 1);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (54, 'Mcgillicuddy Vanilla Schnap', 56.75, 54, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (55, 'Pepper - Black, Whole', 13.51, 55, 3);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (56, 'Bacardi Mojito', 94.55, 56, 3);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (57, 'Potatoes - Fingerling 4 Oz', 77.42, 57, 1);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (58, 'Crackers - Soda / Saltins', 5.83, 58, 1);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (59, 'Flower - Commercial Bronze', 92.22, 59, 1);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (60, 'Cornish Hen', 10.37, 60, 3);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (61, 'Potatoes - Idaho 100 Count', 95.77, 61, 3);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (62, 'Broom And Brush Rack Black', 31.79, 62, 1);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (63, 'Rabbit - Saddles', 74.37, 63, 1);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (64, 'Cheese - Fontina', 58.85, 64, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (65, 'Plaintain', 42.18, 65, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (66, 'Wine - Red, Wolf Blass, Yellow', 86.12, 66, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (67, 'Cup - Translucent 7 Oz Clear', 29.7, 67, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (68, 'Irish Cream - Baileys', 58.24, 68, 1);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (69, 'Spice - Greek 1 Step', 46.0, 69, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (70, 'Appetizer - Crab And Brie', 49.48, 70, 1);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (71, 'Toamtoes 6x7 Select', 89.99, 71, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (72, 'Hot Chocolate - Individual', 43.74, 72, 3);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (73, 'Buffalo - Tenderloin', 30.3, 73, 3);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (74, 'Wine - Red, Pelee Island Merlot', 84.19, 74, 1);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (75, 'Sloe Gin - Mcguinness', 80.4, 75, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (76, 'Chicken - Thigh, Bone In', 98.22, 76, 1);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (77, 'Lamb - Ground', 40.88, 77, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (78, 'Olives - Stuffed', 70.54, 78, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (79, 'Roe - Flying Fish', 68.73, 79, 3);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (80, 'Cheese - St. Paulin', 46.13, 80, 3);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (81, 'Chicken - White Meat With Tender', 37.64, 81, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (82, 'Foam Dinner Plate', 62.84, 82, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (83, 'Pastrami', 34.77, 83, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (84, 'Appetiser - Bought', 95.02, 84, 1);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (85, 'Snapple Lemon Tea', 10.73, 85, 3);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (86, 'Cookie Dough - Peanut Butter', 91.66, 86, 3);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (87, 'Sausage - Andouille', 3.52, 87, 3);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (88, 'Lamb - Shoulder', 59.89, 88, 1);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (89, 'Cheese - Gorgonzola', 99.26, 89, 1);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (90, 'Lychee', 56.94, 90, 1);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (91, 'Juice - Clamato, 341 Ml', 54.46, 91, 2);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (92, 'True - Vue Containers', 69.69, 92, 3);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (93, 'Bacardi Raspberry', 79.67, 93, 3);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (94, 'Trout - Hot Smkd, Dbl Fillet', 4.31, 94, 1);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (95, 'Sugar - Brown', 70.21, 95, 1);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (96, 'Onions - White', 38.94, 96, 1);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (97, 'Mustard - Dry, Powder', 81.31, 97, 3);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (98, 'Rabbit - Saddles', 57.82, 98, 3);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (99, 'Apple - Fuji', 5.9, 99, 1);
insert into Items (ID, Name, Price, DescriptionID, TypeID) values (100, 'Cod - Fillets', 65.37, 100, 3); END";
    }
}
